// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var GraphqlTools           = require("graphql-tools");
var Post$ReasonGraphql     = require("./post.bs.js");
var Query$ReasonGraphql    = require("./query.bs.js");
var Author$ReasonGraphql   = require("./author.bs.js");
var Mutation$ReasonGraphql = require("./mutation.bs.js");

var typeDefs = Query$ReasonGraphql.typeDef + (Mutation$ReasonGraphql.typeDef + (Author$ReasonGraphql.typeDef + Post$ReasonGraphql.typeDef));

var resolvers = {
  Query: Query$ReasonGraphql.resolvers,
  Mutation: Mutation$ReasonGraphql.resolvers,
  Author: Author$ReasonGraphql.resolvers,
  Post: Post$ReasonGraphql.resolvers
};

var schema = GraphqlTools.makeExecutableSchema({
      typeDefs: typeDefs,
      resolvers: resolvers
    });

exports.typeDefs  = typeDefs;
exports.resolvers = resolvers;
exports.schema    = schema;
/* schema Not a pure module */
