// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Post$ReasonGraphql     = require("./post.bs.js");
var Query$ReasonGraphql    = require("./query.bs.js");
var Author$ReasonGraphql   = require("./author.bs.js");
var Mutation$ReasonGraphql = require("./mutation.bs.js");

var typeDefs = Query$ReasonGraphql.typeDef + (Mutation$ReasonGraphql.typeDef + (Author$ReasonGraphql.typeDef + Post$ReasonGraphql.typeDef));

exports.typeDefs = typeDefs;
/* No side effect */
